# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2029764d0739d97da8021d0f07eae40fcb4d2932067cf4e1213e775d278f58a671245b7015ab091bb0bc1c57ffd515398fe1e9a827a6e92c46a85a76972612b

test:
  secret_key_base: 1db08267fdfe1e1b36f93752e4cfbf1aab553ff4185d8f664f2b47216de85d4b03674f3aa5a4df94d8927e9b433c1bce8e702a62bde8684fe9da2016fb27b250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
